### ISSUE TITLE
The 'MDRSREID.Networks.RESIDUAL_NETWORK'

### ISSUE THREAD

**Issue by 5Yesterday** [nickhuang1996/HJL-re-id#13]
File "\HJL-re-id-master\MDRSREID\Networks\create_backbone.py", line 1, in <module>
    from MDRSREID.Networks.RESIDUAL_NETWORK.RESNET.resnet import get_resnet
ModuleNotFoundError: No module named 'MDRSREID.Networks.RESIDUAL_NETWORK'

**Comment by nickhuang1996** [comment]
@5Yesterday I have recovered the code for resnet and hrnet.

**Comment by nickhuang1996** [comment]
@5Yesterday please download this repository again.😁

**Comment by 5Yesterday** [comment]
@nickhuang1996 OK, thanks!
